CC = gcc 
CFLAGS = -Wall -Wextra -pthread -g -O2 
SRCS = $(wildcard src/*.c) 
OBJS = $(SRCS:.c=.o) 
TARGET_SERVER = server 
TARGET_CLIENT = client 
all: $(TARGET_SERVER) $(TARGET_CLIENT) 
$(TARGET_SERVER): $(SRCS)
	 $(CC) $(CFLAGS) -o $(TARGET_SERVER) $(SRCS)
$(TARGET_CLIENT): 
	$(CC) $(CFLAGS) -o $(TARGET_CLIENT) src/client_app.c 
clean: 
	rm -f $(TARGET_SERVER) $(TARGET_CLIENT) src/*.o 
.PHONY: all clean